"""Add sender_email and sender_name to Ticket model

Revision ID: 43ac1d6284da
Revises: 
Create Date: 2024-12-09 11:18:43.874023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43ac1d6284da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_email', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('sender_name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('sender_name')
        batch_op.drop_column('sender_email')

    # ### end Alembic commands ###
